//! Generates the Ink/Stitch compatibility contract page from `conformance/inkstitch-params.toml`, the
//! parameter registry and the SVG adapter, and checks that they agree.
//!
//! The data file holds facts only (names, types, units, defaults, applicability, phases); Ink/Stitch's
//! descriptions are GPL text and are never copied. The registry adds the StitchCraft column. A parameter
//! the registry declares with an Ink/Stitch origin must exist in the data file with a compatible kind and
//! the same default, because defaults are part of the contract (`docs/src/design/params.md` › Naming
//! rules); one with StitchCraft's own origin must not; the lock and method identifiers must match. The
//! SVG adapter's commands must be Ink/Stitch's, and the attributes it reads must be listed.
//!
//! Ink/Stitch gives some keys to several elements, with different defaults (`running_stitch_tolerance_mm`
//! is 0.2 mm on strokes and 0.1 mm on satins), so a declaration is matched with the rows for the stitch
//! types it applies to, never by its key alone.

use std::collections::BTreeSet;

use serde::Deserialize;
use stitchcraft_params::{Family, Kind, Origin, ParamGroup, ParamSpec, StitchType, find};
use stitchcraft_svg::inkstitch::{COMMANDS, READ_ATTRIBUTES};

use crate::param_pages;

/// Where the page is written, relative to the repository root.
pub const PAGE: &str = "docs/src/design/inkstitch-compat-contract.md";
/// The data file, relative to the repository root.
pub const DATA: &str = "conformance/inkstitch-params.toml";

/// The data file's contents.
#[derive(Deserialize)]
pub struct Contract {
    #[serde(default)]
    lock_ids: Vec<String>,
    param: Vec<Param>,
    #[serde(default)]
    method: Vec<Method>,
    #[serde(default)]
    command: Vec<CommandRow>,
    #[serde(default)]
    attribute: Vec<Attribute>,
}

/// One of Ink/Stitch's commands, and where it applies: `object`, `layer` or `document`.
#[derive(Deserialize)]
struct CommandRow {
    name: String,
    tied_to: String,
}

/// An `inkstitch:*` attribute that declares no parameter, its kind (`element`, `pattern`,
/// `stitch_plan`, `sew_stack` or `legacy`) and when StitchCraft plans to read it.
#[derive(Deserialize)]
struct Attribute {
    name: String,
    kind: String,
    phase: String,
    milestone: String,
}

#[derive(Deserialize)]
struct Param {
    element: String,
    name: String,
    #[serde(rename = "type")]
    kind: String,
    unit: String,
    default: String,
    applies_to: Vec<String>,
    phase: String,
    milestone: String,
}

impl Param {
    /// The family of stitch types of the row's element: none for the common settings and clones.
    fn family(&self) -> Option<Family> {
        match self.element.as_str() {
            "stroke" => Some(Family::Stroke),
            "satin" => Some(Family::Satin),
            "fill" => Some(Family::Fill),
            _ => None,
        }
    }

    /// The stitch types the row covers: the ones it lists, or every type of its element when it lists
    /// none (all of them for the common settings, none for clones). Some rows list another parameter's
    /// values instead, such as `custom` for the custom lock shapes; those do not narrow the stitch types.
    /// Only an id of the row's own family names a stitch type, because ids are unique only within a
    /// family: `zigzag` is a lock shape as well as a satin method.
    fn scope(&self) -> BTreeSet<StitchType> {
        let listed: BTreeSet<StitchType> = self.applies_to.iter().filter_map(|a| self.stitch_type(a)).collect();
        if !listed.is_empty() {
            return listed;
        }
        StitchType::ALL.iter().copied().filter(|t| self.element == "common" || self.family() == Some(t.family())).collect()
    }

    /// The stitch type an `applies_to` entry names: an id of the row's own family, or none.
    fn stitch_type(&self, value: &str) -> Option<StitchType> {
        self.family().and_then(|family| StitchType::from_id(family, value))
    }

    /// Whether the row covers any of `types`.
    fn covers(&self, types: &[StitchType]) -> bool {
        let scope = self.scope();
        types.iter().any(|t| scope.contains(t))
    }
}

#[derive(Deserialize)]
struct Method {
    param: String,
    value: String,
    phase: String,
    milestone: String,
}

const SECTIONS: &[(&str, &str)] = &[
    ("common", "All stitch types (ties, locks, trims, stops)"),
    ("stroke", "Strokes: running, ripple, zigzag, manual"),
    ("satin", "Satin columns"),
    ("fill", "Fills"),
    ("clone", "Clones (`<use>`)"),
];

const INTRO: &str = "\
<!-- GENERATED by `cargo xtask docs` from conformance/inkstitch-params.toml. Do not edit by hand. -->

# Ink/Stitch compatibility contract

The parameters an Ink/Stitch SVG can carry, as `inkstitch:<name>` attributes, its other attributes and
its commands, and when StitchCraft supports each one. This is the interoperability contract: StitchCraft's
registry uses these names as its keys so files move between the tools unchanged
([ADR-0001](adr/0001-license-and-clean-room.md)).

- **Checked against:** Ink/Stitch `main` at `d59c9ab` (2026-09-17), 145 parameters.
- **Facts only:** names, types, units, defaults and applicability. Ink/Stitch's descriptions are GPL text
  and are not copied; StitchCraft's own help text lives in the [parameter registry](params.md).
- **Machine-readable source:** `conformance/inkstitch-params.toml`; this page is generated from it and
  from the parameter registry by `cargo xtask docs`, and `cargo xtask docs --check` fails if they disagree:
  a parameter declared with an Ink/Stitch origin must be listed here with a compatible type and the same
  default.
- **StitchCraft** says whether the [parameter registry](../user/reference/params.md) declares the
  parameter. *planned*: not yet; a design that sets it keeps it unchanged and gets `SC-W0105`.
  *registered*: StitchCraft reads and checks it under the same key, meaning and default; it changes the
  stitches once its stitch type or feature lands (see *Phase* and the parameter's reference entry).
  *deviates*: registered, with a meaning that differs as its reference entry describes.
- **Phase** is when the parameter's stitch type lands ([roadmap](../plan/roadmap.md)). `—` means no default
  (the value is derived from another parameter or the shape); `computed` means the default is an expression.
";

impl Contract {
    /// Reads the data file's text.
    pub fn parse(data: &str) -> Result<Contract, String> {
        toml::from_str(data).map_err(|e| format!("{DATA}: {e}"))
    }

    /// Renders the page, with the StitchCraft column from `registry`.
    pub fn render(&self, registry: &[&ParamGroup]) -> String {
        let mut md = String::from(INTRO);
        for (key, title) in SECTIONS {
            md.push_str(&format!(
                "\n## {title}\n\n| Attribute | Type | Unit | Default | Applies to | Phase | StitchCraft |\n|---|---|---|---|---|---|---|\n"
            ));
            for p in self.param.iter().filter(|p| p.element == *key) {
                let applies = if p.applies_to.is_empty() {
                    "all".to_string()
                } else {
                    p.applies_to.iter().map(|a| format!("`{a}`")).collect::<Vec<_>>().join(", ")
                };
                md.push_str(&format!(
                    "| `{}` | {} | {} | {} | {applies} | {} ({}) | {} |\n",
                    p.name,
                    p.kind,
                    p.unit.replace('|', "\\|"),
                    p.default,
                    p.phase,
                    p.milestone,
                    status(registry, p)
                ));
            }
        }
        md.push_str(
            "\n## Method identifiers\n\nThe values the method parameters take (`stroke_method`, `satin_method`, `fill_method`), with phases:\n\n",
        );
        md.push_str("| Parameter | Value | Phase |\n|---|---|---|\n");
        for m in &self.method {
            md.push_str(&format!("| `{}` | `{}` | {} ({}) |\n", m.param, m.value, m.phase, m.milestone));
        }
        let locks = self.lock_ids.iter().map(|l| format!("`{l}`")).collect::<Vec<_>>().join(", ");
        md.push_str(&format!(
            "\nLock stitch identifiers (`lock_start`, `lock_end`): {locks}. StitchCraft accepts every identifier; the shapes are its own\n\
             designs with the same intent, a deviation recorded in the deviations ledger (`conformance/deviations.toml`).\n"
        ));
        md.push_str(
            "\n## Commands\n\nInk/Stitch's command symbols (a `<use>` of the symbol `inkstitch_<name>`), where each applies, and what\n\
             StitchCraft's SVG adapter does with it (`stitchcraft_svg::inkstitch`). Their connectors are never stitched.\n\n\
             | Command | Applies to | StitchCraft |\n|---|---|---|\n",
        );
        for c in &self.command {
            let does = COMMANDS.iter().find(|ours| ours.name == c.name).map_or("planned", |ours| ours.does.describe());
            let applies = match c.tied_to.as_str() {
                "object" => "the object a connector ties it to",
                "layer" => "every layer it is in",
                _ => "the document",
            };
            md.push_str(&format!("| `{}` | {applies} | {does} |\n", c.name));
        }
        md.push_str(
            "\n## Other attributes\n\nThe `inkstitch:*` attributes that declare no parameter: settings of an element, of Ink/Stitch's\n\
             patterns, stitch plan or sew stack, and legacy names Ink/Stitch's updater rewrites in older files.\n\n\
             | Attribute | Kind | Phase | StitchCraft |\n|---|---|---|---|\n",
        );
        for a in &self.attribute {
            let (phase, ours) = match (READ_ATTRIBUTES.contains(&a.name.as_str()), a.milestone.as_str()) {
                (true, _) => (format!("{} ({})", a.phase, a.milestone), "read"),
                (false, "—") => ("—".to_string(), "not planned"),
                (false, _) => (format!("{} ({})", a.phase, a.milestone), "planned"),
            };
            md.push_str(&format!("| `{}` | {} | {phase} | {ours} |\n", a.name, a.kind.replace('_', " ")));
        }
        let registered = self.param.iter().filter(|p| declaration(registry, p).is_some()).count();
        md.push_str(&format!("\n_{} parameter declarations, {registered} registered in StitchCraft._\n", self.param.len()));
        md
    }

    /// Where `registry` and the data file disagree, one line each.
    pub fn check(&self, registry: &[&ParamGroup]) -> Vec<String> {
        let mut problems = Vec::new();
        for spec in registry.iter().flat_map(|g| g.specs) {
            let key = spec.key;
            let named = self.param.iter().any(|p| p.name == key);
            match (spec.origin, named) {
                (Origin::StitchCraft, false) => {}
                (Origin::StitchCraft, true) => {
                    problems.push(format!("`{key}` is an Ink/Stitch parameter ({DATA}): declare it with an Ink/Stitch origin"));
                }
                (_, false) => problems.push(format!("`{key}` is declared with an Ink/Stitch origin, but {DATA} has no such parameter")),
                (origin, true) => {
                    let rows: Vec<&Param> = self.param.iter().filter(|p| p.name == key && p.covers(spec.applies_to)).collect();
                    let uncovered: Vec<String> =
                        spec.applies_to.iter().filter(|t| !rows.iter().any(|p| p.covers(&[**t]))).map(|t| format!("`{}`", t.id())).collect();
                    if !uncovered.is_empty() {
                        problems.push(format!("`{key}` applies to {} here, but Ink/Stitch does not give it that stitch type", uncovered.join(", ")));
                    }
                    for p in rows {
                        for problem in disagreements(spec, origin, p) {
                            if !problems.contains(&problem) {
                                problems.push(problem);
                            }
                        }
                    }
                }
            }
        }
        for key in ["lock_start", "lock_end"] {
            if let Some(Kind::Choice { options }) = find(registry, key).map(|spec| spec.kind) {
                let ids: Vec<&str> = options.iter().map(|o| o.id).collect();
                if ids != self.lock_ids {
                    problems.push(format!("`{key}` offers {ids:?}, but the lock identifiers in {DATA} are {:?}", self.lock_ids));
                }
            }
        }
        for family in [Family::Stroke, Family::Satin, Family::Fill] {
            let ours: BTreeSet<&str> = StitchType::ALL.iter().filter(|t| t.family() == family).map(|t| t.id()).collect();
            let listed: Vec<&str> = self.method.iter().filter(|m| m.param == family.method_param()).map(|m| m.value.as_str()).collect();
            let theirs: BTreeSet<&str> = listed.iter().copied().collect();
            if ours != theirs {
                problems.push(format!("`{}`: StitchType has {ours:?}, but {DATA} lists {theirs:?}", family.method_param()));
            }
            // A registered method parameter offers them in Ink/Stitch's order, which its defaults count on.
            if let Some(Kind::Choice { options }) = find(registry, family.method_param()).map(|spec| spec.kind) {
                let offered: Vec<&str> = options.iter().map(|o| o.id).collect();
                if offered != listed {
                    problems.push(format!("`{}` offers {offered:?}, but Ink/Stitch's order is {listed:?}", family.method_param()));
                }
            }
        }
        let ours: BTreeSet<&str> = COMMANDS.iter().map(|c| c.name).collect();
        let theirs: BTreeSet<&str> = self.command.iter().map(|c| c.name.as_str()).collect();
        if ours != theirs {
            problems.push(format!("the SVG adapter knows the commands {ours:?}, but {DATA} lists {theirs:?}"));
        }
        for name in READ_ATTRIBUTES {
            if !self.attribute.iter().any(|a| a.name == *name) {
                problems.push(format!("the SVG adapter reads `{name}`, which {DATA} does not list as an attribute"));
            }
        }
        problems
    }
}

/// Where a declaration and the Ink/Stitch row it matches disagree on the kind or the default, on
/// applying to every stitch type, or on when a settings window shows it.
fn disagreements(spec: &ParamSpec, origin: Origin, p: &Param) -> Vec<String> {
    let key = spec.key;
    let mut problems = Vec::new();
    if !compatible(spec.kind, &p.kind, &p.unit) {
        problems.push(format!("`{key}` is {} here, but Ink/Stitch's is a {} in {}", spec.kind.describe(), p.kind, p.unit));
    }
    let their_default = if p.default == "—" { "" } else { p.default.as_str() };
    // Ink/Stitch gives some combo boxes their default as a place in the options, which the registry lists
    // in Ink/Stitch's order (`check` makes sure of it for the method parameters). It reads a toggle that
    // declares no default, such as `satin_column`, as off when the attribute is missing.
    let their_default = match (spec.kind, p.kind.as_str(), their_default.parse::<usize>()) {
        (Kind::Choice { options }, "combo", Ok(place)) => options.get(place).map_or(their_default, |o| o.id),
        (Kind::Toggle, _, _) if their_default.is_empty() => "false",
        _ => their_default,
    };
    // Ink/Stitch declares some parameters once for each kind of element, each with its own default; the
    // registry gives such a family its own default.
    let our_default = p.family().map_or(spec.default, |family| spec.default_for(family));
    let same = match (spec.read(our_default), spec.read(their_default)) {
        (Ok((ours, _)), Ok((theirs, None))) => ours == theirs,
        _ => false,
    };
    if origin == Origin::InkStitch && !same {
        problems.push(format!(
            "`{key}` defaults to \"{our_default}\" here and \"{their_default}\" in Ink/Stitch: defaults are part of the contract (declare a deviation if the difference is deliberate)"
        ));
    }
    if p.element == "common" && spec.applies_to != StitchType::ALL {
        problems.push(format!("`{key}` applies to every stitch type in Ink/Stitch, but not here"));
    }
    // Values in `applies_to` that are not stitch types are another parameter's values Ink/Stitch shows
    // this one for (a lock's size, say, only for the shapes it sizes); the registry must say the same.
    let theirs: BTreeSet<&str> = p.applies_to.iter().map(String::as_str).filter(|a| p.stitch_type(a).is_none()).collect();
    let ours: BTreeSet<&str> = spec.visible_when.map(|c| c.any_of.iter().copied().collect()).unwrap_or_default();
    if !theirs.is_empty() && theirs != ours {
        let here = if ours.is_empty() { "always".to_string() } else { format!("only for {ours:?}") };
        problems.push(format!("`{key}` is shown only for {theirs:?} in Ink/Stitch, but {here} here"));
    }
    problems
}

/// The registry's declaration of `row`'s key for the stitch types the row covers, with its group.
fn declaration<'r>(registry: &[&'r ParamGroup], row: &Param) -> Option<(&'r ParamGroup, &'static ParamSpec)> {
    registry.iter().find_map(|group| group.specs.iter().find(|s| s.key == row.name && row.covers(s.applies_to)).map(|spec| (*group, spec)))
}

/// The StitchCraft column: planned, or a link to the declaration's reference entry.
fn status(registry: &[&ParamGroup], row: &Param) -> String {
    let Some((group, spec)) = declaration(registry, row) else { return "planned".to_string() };
    let word = if matches!(spec.origin, Origin::InkStitchDeviates { .. }) { "deviates" } else { "registered" };
    format!("[{word}](../user/reference/{})", param_pages::anchor(group, &row.name))
}

/// Whether a StitchCraft kind can hold the values of an Ink/Stitch type and unit.
fn compatible(kind: Kind, their_type: &str, unit: &str) -> bool {
    match kind {
        Kind::Length { .. } => their_type == "float" && matches!(unit, "mm" | "mm/cycle"),
        Kind::LengthList { .. } => matches!(their_type, "float" | "string" | "str") && unit.starts_with("mm"),
        Kind::LengthPair { .. } => their_type == "float" && unit == "mm (each side)",
        Kind::PercentPair { .. } => their_type == "float" && unit == "% (each side)",
        Kind::PercentList { .. } => their_type == "float" && unit == "%",
        Kind::Angle => their_type == "float" && matches!(unit, "deg" | "degrees" | "°"),
        Kind::Percent { .. } => their_type == "float" && matches!(unit, "%" | "± %"),
        // Ink/Stitch reads some numbers as floats that its settings window shows as whole numbers, such as a
        // fill's staggers, whose fractions it documents.
        Kind::Number { .. } => matches!(their_type, "float" | "int") && unit == "—",
        Kind::Count { .. } => their_type == "int",
        Kind::CountList { .. } => matches!(their_type, "int" | "string" | "str"),
        Kind::Toggle => matches!(their_type, "boolean" | "toggle"),
        Kind::Choice { .. } => matches!(their_type, "combo" | "dropdown"),
        Kind::Seed => their_type == "random_seed",
        Kind::Text { .. } => matches!(their_type, "string" | "str"),
    }
}

#[cfg(test)]
mod tests {
    use stitchcraft_params::{ChoiceOption, Condition, ParamSpec, Stability};

    use super::*;

    /// A data file with one fill parameter, one lock id and every method id (so only what a test
    /// changes disagrees).
    fn data(default: &str) -> String {
        let mut data = format!(
            "lock_ids = [\"half_stitch\"]\n[[param]]\nelement = \"fill\"\nname = \"row_spacing_mm\"\ntype = \"float\"\nunit = \"mm\"\n\
             default = \"{default}\"\napplies_to = [\"tatami_fill\"]\nphase = \"P1\"\nmilestone = \"M5\"\n"
        );
        for t in StitchType::ALL {
            let param = t.family().method_param();
            data.push_str(&format!("[[method]]\nparam = \"{param}\"\nvalue = \"{}\"\nphase = \"P1\"\nmilestone = \"M5\"\n", t.id()));
        }
        for c in COMMANDS {
            data.push_str(&format!("[[command]]\nname = \"{}\"\ntied_to = \"object\"\n", c.name));
        }
        for a in READ_ATTRIBUTES {
            data.push_str(&format!("[[attribute]]\nname = \"{a}\"\nkind = \"element\"\nphase = \"P1\"\nmilestone = \"M3\"\n"));
        }
        data
    }

    const ROW_SPACING: ParamSpec = ParamSpec {
        key: "row_spacing_mm",
        label: "Row spacing",
        help: " Distance between rows.\n",
        kind: Kind::Length { min: 0.1, max: 10.0, optional: false },
        default: "0.25",
        family_defaults: &[],
        group: "Fill",
        applies_to: &[StitchType::TatamiFill],
        visible_when: None,
        stability: Stability::Stable,
        origin: Origin::InkStitch,
    };

    fn registry(specs: &'static [ParamSpec]) -> ParamGroup {
        ParamGroup { name: "TatamiFillParams", help: " Tatami.\n", applies_to: &[StitchType::TatamiFill], specs }
    }

    #[test]
    fn renders_sections_methods_counts_and_status() {
        let contract = Contract::parse(&data("0.25")).unwrap();
        let planned = contract.render(&[]);
        assert!(planned.contains("| `row_spacing_mm` | float | mm | 0.25 | `tatami_fill` | P1 (M5) | planned |"));
        assert!(planned.contains("| `fill_method` | `tatami_fill` | P1 (M5) |"));
        assert!(planned.contains("_1 parameter declarations, 0 registered in StitchCraft._"));
        assert!(planned.contains("| `trim` | the object a connector ties it to | applied: turns on `trim_after` |"));
        assert!(planned.contains("| `ignore_object` | element | P1 (M3) | read |"));
        let group = registry(&[ROW_SPACING]);
        let registered = contract.render(&[&group]);
        assert!(registered.contains("| P1 (M5) | [registered](../user/reference/params/tatami-fill.md#row_spacing_mm) |"));
        const DEVIATES: &[ParamSpec] = &[ParamSpec { origin: Origin::InkStitchDeviates { deviation: "DEV-FILL-001" }, ..ROW_SPACING }];
        let group = registry(DEVIATES);
        assert!(contract.render(&[&group]).contains("| [deviates](../user/reference/params/tatami-fill.md#row_spacing_mm) |"));
    }

    /// A key Ink/Stitch uses on two elements with different defaults (satin's row first), and our
    /// declaration of it for running and ripple stitches.
    fn shared(default: &'static str) -> (String, ParamGroup) {
        let row = |element: &str, default: &str, applies_to: &str, milestone: &str| {
            format!(
                "[[param]]\nelement = \"{element}\"\nname = \"running_stitch_tolerance_mm\"\ntype = \"float\"\nunit = \"mm\"\n\
                 default = \"{default}\"\napplies_to = [{applies_to}]\nphase = \"P1\"\nmilestone = \"{milestone}\"\n"
            )
        };
        let rows = row("satin", "0.1", "", "M4") + &row("stroke", "0.2", "\"running_stitch\", \"ripple_stitch\"", "M3");
        let data = data("0.25").replacen("[[param]]", &format!("{rows}[[param]]"), 1);
        let spec = ParamSpec {
            key: "running_stitch_tolerance_mm",
            default,
            applies_to: &[StitchType::RunningStitch, StitchType::RippleStitch],
            ..ROW_SPACING
        };
        let specs: &'static [ParamSpec] = Box::leak(Box::new([spec]));
        (data, ParamGroup { name: "RunningParams", help: " Running.\n", applies_to: &[StitchType::RunningStitch], specs })
    }

    #[test]
    fn keys_shared_by_elements_match_by_stitch_type() {
        let (data, group) = shared("0.2");
        let contract = Contract::parse(&data).unwrap();
        let page = contract.render(&[&group]);
        assert!(page.contains("| `running_stitch_tolerance_mm` | float | mm | 0.1 | all | P1 (M4) | planned |"), "satin's is not ours");
        assert!(page.contains("| P1 (M3) | [registered](../user/reference/params/running.md#running_stitch_tolerance_mm) |"));
        assert!(page.contains("_3 parameter declarations, 1 registered in StitchCraft._"));
        assert_eq!(contract.check(&[&group]), Vec::<String>::new(), "compared with the stroke's default, not the satin's");
        let (data, group) = shared("0.1");
        assert_eq!(
            Contract::parse(&data).unwrap().check(&[&group]),
            [
                "`running_stitch_tolerance_mm` defaults to \"0.1\" here and \"0.2\" in Ink/Stitch: defaults are part of the contract (declare a deviation if the difference is deliberate)"
            ]
        );
    }

    #[test]
    fn a_family_with_its_own_default_is_compared_with_its_element_s_row() {
        // Declared for satin columns too, with their own default: each row is compared with its family's.
        let (data, _) = shared("0.2");
        let both = |family_defaults: &'static [(Family, &'static str)]| {
            let spec = ParamSpec {
                key: "running_stitch_tolerance_mm",
                default: "0.2",
                family_defaults,
                applies_to: &[StitchType::RunningStitch, StitchType::RippleStitch, StitchType::SatinColumn],
                ..ROW_SPACING
            };
            let specs: &'static [ParamSpec] = Box::leak(Box::new([spec]));
            ParamGroup { name: "RunningParams", help: " Running.\n", applies_to: &[StitchType::RunningStitch], specs }
        };
        let contract = Contract::parse(&data).unwrap();
        assert_eq!(contract.check(&[&both(&[(Family::Satin, "0.1")])]), Vec::<String>::new());
        assert_eq!(
            contract.check(&[&both(&[])]),
            [
                "`running_stitch_tolerance_mm` defaults to \"0.2\" here and \"0.1\" in Ink/Stitch: defaults are part of the contract (declare a deviation if the difference is deliberate)"
            ]
        );
    }

    #[test]
    fn a_declaration_for_stitch_types_ink_stitch_does_not_give_the_key_is_reported() {
        const WIDER: &[ParamSpec] = &[ParamSpec { applies_to: &[StitchType::TatamiFill, StitchType::ContourFill], ..ROW_SPACING }];
        let group = registry(WIDER);
        assert_eq!(
            Contract::parse(&data("0.25")).unwrap().check(&[&group]),
            ["`row_spacing_mm` applies to `contour_fill` here, but Ink/Stitch does not give it that stitch type"]
        );
    }

    #[test]
    fn agreeing_registries_have_no_problems_and_numbers_compare_as_numbers() {
        let group = registry(&[ROW_SPACING]);
        assert_eq!(Contract::parse(&data("0.25")).unwrap().check(&[&group]), Vec::<String>::new());
        assert_eq!(Contract::parse(&data("0.250")).unwrap().check(&[&group]), Vec::<String>::new());
    }

    #[test]
    fn a_toggle_ink_stitch_gives_no_default_is_off() {
        let data = data("0.25").replacen(
            "[[param]]",
            "[[param]]\nelement = \"fill\"\nname = \"fill_underlay\"\ntype = \"toggle\"\nunit = \"—\"\ndefault = \"—\"\n\
             applies_to = [\"tatami_fill\"]\nphase = \"P1\"\nmilestone = \"M5\"\n[[param]]",
            1,
        );
        let contract = Contract::parse(&data).unwrap();
        const OFF: &[ParamSpec] = &[ROW_SPACING, ParamSpec { key: "fill_underlay", kind: Kind::Toggle, default: "false", ..ROW_SPACING }];
        const ON: &[ParamSpec] = &[ROW_SPACING, ParamSpec { key: "fill_underlay", kind: Kind::Toggle, default: "true", ..ROW_SPACING }];
        assert_eq!(contract.check(&[&registry(OFF)]), Vec::<String>::new());
        assert_eq!(
            contract.check(&[&registry(ON)]),
            [
                "`fill_underlay` defaults to \"true\" here and \"false\" in Ink/Stitch: defaults are part of the contract (declare a deviation if the difference is deliberate)"
            ]
        );
    }

    #[test]
    fn every_disagreement_is_reported() {
        const SPECS: &[ParamSpec] = &[
            ParamSpec { kind: Kind::Count { min: 1, max: 9 }, default: "1", ..ROW_SPACING },
            ParamSpec { key: "sparkle_mm", ..ROW_SPACING },
            ParamSpec {
                key: "lock_start",
                kind: Kind::Choice { options: &[ChoiceOption { id: "bowtie", label: "Bowtie" }] },
                default: "bowtie",
                origin: Origin::StitchCraft,
                ..ROW_SPACING
            },
        ];
        let group = registry(SPECS);
        let mut data = data("0.25");
        data = data.replace("value = \"legacy_fill\"", "value = \"old_fill\"");
        let problems = Contract::parse(&data).unwrap().check(&[&group]);
        assert_eq!(
            problems,
            [
                "`row_spacing_mm` is a whole number from 1 to 9 here, but Ink/Stitch's is a float in mm",
                "`row_spacing_mm` defaults to \"1\" here and \"0.25\" in Ink/Stitch: defaults are part of the contract (declare a deviation if the difference is deliberate)",
                "`sparkle_mm` is declared with an Ink/Stitch origin, but conformance/inkstitch-params.toml has no such parameter",
                "`lock_start` offers [\"bowtie\"], but the lock identifiers in conformance/inkstitch-params.toml are [\"half_stitch\"]",
                "`fill_method`: StitchType has {\"circular_fill\", \"contour_fill\", \"cross_stitch\", \"guided_fill\", \"legacy_fill\", \"linear_gradient_fill\", \"meander_fill\", \"tartan_fill\", \"tatami_fill\"}, but conformance/inkstitch-params.toml lists {\"circular_fill\", \"contour_fill\", \"cross_stitch\", \"guided_fill\", \"linear_gradient_fill\", \"meander_fill\", \"old_fill\", \"tartan_fill\", \"tatami_fill\"}",
            ]
        );
    }

    #[test]
    fn a_parameter_ink_stitch_shows_only_for_some_values_is_shown_for_the_same() {
        let data = data("0.25").replacen(
            "[[param]]",
            "[[param]]\nelement = \"common\"\nname = \"lock_start_scale_mm\"\ntype = \"float\"\nunit = \"mm\"\ndefault = \"0.7\"\n\
             applies_to = [\"back_forth\", \"custom\"]\nphase = \"P1\"\nmilestone = \"M3\"\n[[param]]",
            1,
        );
        let contract = Contract::parse(&data).unwrap();
        let size = |any_of: Option<&'static [&'static str]>| -> ParamGroup {
            let spec = ParamSpec {
                key: "lock_start_scale_mm",
                default: "0.7",
                applies_to: StitchType::ALL,
                visible_when: any_of.map(|any_of| Condition { key: "lock_start", any_of }),
                ..ROW_SPACING
            };
            ParamGroup { name: "CommonParams", help: " Common.\n", applies_to: StitchType::ALL, specs: Box::leak(Box::new([spec])) }
        };
        assert_eq!(contract.check(&[&size(Some(&["custom", "back_forth"]))]), Vec::<String>::new(), "in any order");
        assert_eq!(
            contract.check(&[&size(None)]),
            ["`lock_start_scale_mm` is shown only for {\"back_forth\", \"custom\"} in Ink/Stitch, but always here"]
        );
        assert_eq!(
            contract.check(&[&size(Some(&["custom"]))]),
            ["`lock_start_scale_mm` is shown only for {\"back_forth\", \"custom\"} in Ink/Stitch, but only for {\"custom\"} here"]
        );
        // `zigzag` is a lock shape here, though a satin method has the same id.
        let zigzag = self::data("0.25").replacen(
            "[[param]]",
            "[[param]]\nelement = \"common\"\nname = \"lock_start_scale_mm\"\ntype = \"float\"\nunit = \"mm\"\ndefault = \"0.7\"\n\
             applies_to = [\"zigzag\", \"custom\"]\nphase = \"P1\"\nmilestone = \"M3\"\n[[param]]",
            1,
        );
        assert_eq!(Contract::parse(&zigzag).unwrap().check(&[&size(Some(&["custom", "zigzag"]))]), Vec::<String>::new());
    }

    #[test]
    fn a_lock_shape_named_like_a_satin_method_is_not_a_stitch_type() {
        // The lock sizes are shown for some lock shapes, `zigzag` among them, which is also a satin
        // method's id: in a common row it is a lock shape, in a satin row the satin method.
        let row = |element: &str| Param {
            element: element.to_string(),
            name: "lock_start_scale_percent".to_string(),
            kind: "float".to_string(),
            unit: "%".to_string(),
            default: "100".to_string(),
            applies_to: vec!["arrow".to_string(), "zigzag".to_string()],
            phase: "P1".to_string(),
            milestone: "M3".to_string(),
        };
        assert_eq!(row("common").scope().len(), StitchType::ALL.len());
        assert_eq!(row("satin").scope().into_iter().collect::<Vec<_>>(), [StitchType::SatinZigzag]);
        let strokes = row("stroke").scope();
        assert!(strokes.len() == 4 && strokes.iter().all(|t| t.family() == Family::Stroke), "no stroke method listed: every stroke type");
    }

    #[test]
    fn a_method_parameter_offers_ink_stitch_s_methods_in_its_order_from_its_place_default() {
        let data = data("0.25").replacen(
            "[[param]]",
            "[[param]]\nelement = \"fill\"\nname = \"fill_method\"\ntype = \"combo\"\nunit = \"—\"\ndefault = \"0\"\n\
             applies_to = []\nphase = \"P1\"\nmilestone = \"M5\"\n[[param]]",
            1,
        );
        let contract = Contract::parse(&data).unwrap();
        let fills = |order: &[StitchType], default: &'static str| -> ParamGroup {
            let options: Vec<ChoiceOption> = order.iter().map(|t| ChoiceOption { id: t.id(), label: t.name() }).collect();
            let fills: Vec<StitchType> = StitchType::ALL.iter().copied().filter(|t| t.family() == Family::Fill).collect();
            let spec = ParamSpec {
                key: "fill_method",
                kind: Kind::Choice { options: Box::leak(options.into_boxed_slice()) },
                default,
                applies_to: Box::leak(fills.into_boxed_slice()),
                ..ROW_SPACING
            };
            ParamGroup { name: "FillParams", help: " Fill.\n", applies_to: &[StitchType::TatamiFill], specs: Box::leak(Box::new([spec])) }
        };
        let order: Vec<StitchType> =
            contract.method.iter().filter(|m| m.param == "fill_method").map(|m| StitchType::from_id(Family::Fill, &m.value).unwrap()).collect();
        assert_eq!(contract.check(&[&fills(&order, "tatami_fill")]), Vec::<String>::new(), "Ink/Stitch's 0 is the first method");
        assert_eq!(
            contract.check(&[&fills(&order, "contour_fill")]),
            [
                "`fill_method` defaults to \"contour_fill\" here and \"tatami_fill\" in Ink/Stitch: defaults are part of the contract (declare a deviation if the difference is deliberate)"
            ]
        );
        let mut reordered = order;
        reordered.swap(0, 1);
        let problems = contract.check(&[&fills(&reordered, reordered[0].id())]);
        assert_eq!(problems.len(), 1, "{problems:?}");
        let expected = format!("`fill_method` offers [\"{}\", \"{}\"", reordered[0].id(), reordered[1].id());
        assert!(problems[0].starts_with(&expected), "{problems:?}");
    }

    #[test]
    fn stitchcraft_parameters_may_not_take_ink_stitch_keys() {
        const OURS: &[ParamSpec] = &[ParamSpec { origin: Origin::StitchCraft, ..ROW_SPACING }];
        let group = registry(OURS);
        assert_eq!(
            Contract::parse(&data("0.25")).unwrap().check(&[&group]),
            ["`row_spacing_mm` is an Ink/Stitch parameter (conformance/inkstitch-params.toml): declare it with an Ink/Stitch origin"]
        );
    }

    #[test]
    fn the_engine_registry_agrees_with_the_committed_contract() {
        let data = crate::util::read(&crate::util::root().join(DATA)).unwrap();
        let registry = stitchcraft_engine::registry::PARAMETERS;
        assert_eq!(Contract::parse(&data).unwrap().check(registry), Vec::<String>::new());
    }

    #[test]
    fn the_svg_adapter_s_commands_and_attributes_must_be_listed() {
        let data = data("0.25");
        let missing =
            data.replace("name = \"trim\"\ntied_to", "name = \"cut\"\ntied_to").replace("name = \"ignore_object\"\nkind", "name = \"x\"\nkind");
        let problems = Contract::parse(&missing).unwrap().check(&[]);
        assert_eq!(problems.len(), 2, "{problems:?}");
        assert!(problems[0].starts_with("the SVG adapter knows the commands {"), "{problems:?}");
        assert_eq!(problems[1], "the SVG adapter reads `ignore_object`, which conformance/inkstitch-params.toml does not list as an attribute");
        // Attributes not read: planned, or not planned at all.
        let more = format!(
            "{data}[[attribute]]\nname = \"stroke_first\"\nkind = \"element\"\nphase = \"P1\"\nmilestone = \"M5\"\n\
                            [[attribute]]\nname = \"sew_stack\"\nkind = \"sew_stack\"\nphase = \"—\"\nmilestone = \"—\"\n"
        );
        let page = Contract::parse(&more).unwrap().render(&[]);
        assert!(page.contains("| `stroke_first` | element | P1 (M5) | planned |"), "{page}");
        assert!(page.contains("| `sew_stack` | sew stack | — | not planned |"), "{page}");
    }

    #[test]
    fn bad_data_is_an_error() {
        assert!(Contract::parse("param = 3").is_err());
    }
}
