//! Generates the parameter reference from the engine's registry: one page per `params!` declaration, an
//! index of every key, and a JSON Schema for programs (`docs/src/design/params.md` › Generated
//! outputs). The help text, labels, ranges and defaults all come from the declarations, so the
//! reference cannot drift from the code.

use std::fmt::Write as _;

use serde_json::{Value as Json, json};
use stitchcraft_engine::registry::PARAMETERS;
use stitchcraft_params::{Kind, MAX_LIST, Origin, ParamGroup, ParamSpec, Stability, StitchType, Value};

use crate::deviations::{self, Deviation};

/// The reference directory, relative to the repository root.
const REFERENCE: &str = "docs/src/user/reference";
/// The directory of the per-declaration pages, relative to the repository root. Every page in it is
/// generated; `cargo xtask docs` deletes (and `--check` reports) pages no declaration produces.
pub const DIR: &str = "docs/src/user/reference/params";

const INDEX_INTRO: &str = "\
Every setting a design element can carry, by the key a design stores it under. A parameter that Ink/Stitch
also has keeps Ink/Stitch's key, meaning and default, so files move between the two tools unchanged
([compatibility contract](../../design/inkstitch-compat-contract.md)).

StitchCraft never falls back to a default in silence. A value it cannot use is an error that says what is
accepted ([`SC-E0101`](diagnostics.md#sc-e0101)); a value outside its range is clamped, with a warning
([`SC-W0102`](diagnostics.md#sc-w0102)); a key it does not know is kept unchanged, with a warning
([`SC-W0105`](diagnostics.md#sc-w0105)).

## Writing values

Designs store every value as text, the same way for every host:

- **Lengths** are millimetres. They may carry a unit: `2.5`, `2.5mm`, `0.1in` and `7pt` are all accepted.
- **Angles** are degrees (`45`, `45°` or `45deg`), turned into the range from −180 (exclusive) to 180.
- **Percentages** may end in `%`.
- **On or off** is `true` or `false`; `yes`/`no`, `on`/`off` and `1`/`0` work too.
- **Lists** (several lengths or numbers) are separated by spaces or commas: `2.5 1.2`.
- **Seeds** are a number or any text; empty means \"derive it from the element\", so every element
  differs but every run is the same.

Programs that store values as JSON (and the [JSON Schema](params.schema.json) that describes them) use
numbers, `true`/`false`, strings and arrays instead, and `null` for an empty value.
";

/// Every generated file: the index, a page per declaration and the JSON Schema. Deviating parameters show
/// their entry in `ledger`.
pub fn pages(ledger: &[Deviation]) -> Result<Vec<(String, String)>, String> {
    let mut pages = vec![(format!("{REFERENCE}/params.md"), index())];
    for group in PARAMETERS {
        pages.push((format!("{DIR}/{}.md", slug(group)), page(group, ledger)?));
    }
    pages.push((format!("{REFERENCE}/params.schema.json"), schema()?));
    Ok(pages)
}

/// Where `group`'s page describes `key`, relative to the reference directory: `params/common.md#ties`.
pub fn anchor(group: &ParamGroup, key: &str) -> String {
    format!("params/{}.md#{key}", slug(group))
}

/// `CommonParams` → `common`; `TatamiFillParams` → `tatami-fill`.
fn slug(group: &ParamGroup) -> String {
    words(group).join("-")
}

/// `CommonParams` → `Common parameters`; `TatamiFillParams` → `Tatami fill parameters`.
fn title(group: &ParamGroup) -> String {
    let mut title = words(group).join(" ");
    if let Some(first) = title.get(..1) {
        title = format!("{}{}", first.to_ascii_uppercase(), title.get(1..).unwrap_or(""));
    }
    format!("{title} parameters")
}

/// The words of a declaration's name, lower case, without the `Params` suffix (REQ-PRM-001 requires it).
fn words(group: &ParamGroup) -> Vec<String> {
    let stem = group.name.strip_suffix("Params").unwrap_or(group.name);
    let mut words: Vec<String> = Vec::new();
    for c in stem.chars() {
        match words.last_mut() {
            Some(word) if !c.is_ascii_uppercase() => word.push(c),
            _ => words.push(c.to_ascii_lowercase().to_string()),
        }
    }
    words
}

fn header(source: &str) -> String {
    format!("<!-- Generated by `cargo xtask docs` from {source}. Edit the declaration, not this page. -->\n\n")
}

fn index() -> String {
    let mut out = header("the parameter registry (`stitchcraft-engine/src/registry.rs`)");
    out.push_str("# Parameters\n\n");
    out.push_str(INDEX_INTRO);
    out.push_str("\n## Groups\n\n| Group | Parameters | Applies to |\n|---|---|---|\n");
    for group in PARAMETERS {
        let _ = writeln!(out, "| [{}](params/{}.md) | {} | {} |", title(group), slug(group), group.specs.len(), applies_to(group.applies_to));
    }
    out.push_str("\n## Every parameter\n\n| Key | Label | Group |\n|---|---|---|\n");
    let mut rows: Vec<(&str, &str, &ParamGroup)> = PARAMETERS.iter().flat_map(|g| g.specs.iter().map(move |s| (s.key, s.label, *g))).collect();
    rows.sort_by_key(|(key, _, _)| *key);
    for (key, label, group) in rows {
        let _ = writeln!(out, "| [`{key}`](params/{}.md#{key}) | {label} | {} |", slug(group), title(group));
    }
    out
}

fn page(group: &ParamGroup, ledger: &[Deviation]) -> Result<String, String> {
    let mut out = header(&format!("`{}` in the parameter registry", group.name));
    let _ = writeln!(out, "# {}\n\n{}\n\nApplies to {}.", title(group), group.help(), applies_to(group.applies_to));
    let mut section = "";
    for spec in group.specs {
        if spec.group != section {
            section = spec.group;
            let _ = writeln!(out, "\n## {section}");
        }
        let _ = writeln!(out, "\n### `{}`\n\n**{}.** {}\n", spec.key, spec.label, spec.help());
        let _ = writeln!(out, "- **Accepts:** {}", accepts(spec));
        let _ = writeln!(out, "- **Default:** {}", default(spec)?);
        if let Some(condition) = spec.visible_when {
            let _ = writeln!(out, "- **Shown when** [`{0}`](#{0}) is {1}", condition.key, either(condition.any_of));
        }
        if spec.applies_to != group.applies_to {
            let _ = writeln!(out, "- **Applies to:** {}", applies_to(spec.applies_to));
        }
        let origin = match spec.origin {
            Origin::InkStitch => "same key, meaning and default".to_string(),
            Origin::InkStitchDeviates { deviation } => {
                // `cargo xtask docs` reports an id missing from the ledger; the page still renders.
                let summary = deviations::summary(ledger, deviation).unwrap_or("see the deviations ledger");
                format!("same key; StitchCraft differs ({deviation}): {summary}")
            }
            Origin::StitchCraft => "none; this is StitchCraft's own".to_string(),
        };
        let _ = writeln!(out, "- **Ink/Stitch:** {origin}");
        match spec.stability {
            Stability::Stable => {}
            Stability::Experimental => out.push_str("- **Experimental:** designs that use it may stitch differently in a later version\n"),
            Stability::Deprecated { use_instead: Some(other) } => {
                let _ = writeln!(out, "- **Deprecated:** use [`{other}`](#{other}) instead");
            }
            Stability::Deprecated { use_instead: None } => out.push_str("- **Deprecated:** no longer needed\n"),
        }
    }
    Ok(out)
}

/// What a parameter accepts, for people: the validation messages' wording, with option labels added, and
/// what a family that needs a value accepts instead (`ParamSpec::in_family`).
fn accepts(spec: &ParamSpec) -> String {
    let describe = |kind: Kind| match kind {
        Kind::Choice { options } => {
            let options: Vec<String> = options.iter().map(|o| format!("`{}` ({})", o.id, o.label)).collect();
            format!("one of {}", options.join(", "))
        }
        other => other.describe(),
    };
    let mut text = describe(spec.kind);
    for &(family, _) in spec.family_defaults {
        let kind = spec.in_family(family).kind;
        if kind != spec.kind {
            let _ = write!(text, "; for {}, {}, empty being the default", family.plural(), describe(kind));
        }
    }
    text
}

/// The default as a design stores it, with each family's own; an empty default is explained by the help
/// text.
fn default(spec: &ParamSpec) -> Result<String, String> {
    let shown = |value: &str| -> Result<String, String> {
        // The registry test guarantees defaults parse; this keeps a broken one from reaching the docs.
        spec.read(value).map_err(|d| format!("`{}`: {}", spec.key, d.message))?;
        Ok(if value.is_empty() { "empty".to_string() } else { format!("`{value}`") })
    };
    let mut text = shown(spec.default)?;
    for &(family, value) in spec.family_defaults {
        let _ = write!(text, ", and {} for {}", shown(value)?, family.plural());
    }
    Ok(text)
}

/// `values` as code, joined the way a sentence lists alternatives: "`a`", "`a` or `b`", "`a`, `b` or `c`".
fn either(values: &[&str]) -> String {
    let code: Vec<String> = values.iter().map(|v| format!("`{v}`")).collect();
    match code.split_last() {
        Some((last, rest)) if !rest.is_empty() => format!("{} or {last}", rest.join(", ")),
        _ => code.concat(),
    }
}

fn applies_to(types: &[StitchType]) -> String {
    if types == StitchType::ALL { "every stitch type".to_string() } else { types.iter().map(|t| t.name()).collect::<Vec<_>>().join(", ") }
}

/// The JSON Schema of an element's parameters as JSON values, for programs: editors, presets, hosts.
fn schema() -> Result<String, String> {
    let mut properties = serde_json::Map::new();
    for spec in PARAMETERS.iter().flat_map(|g| g.specs) {
        properties.insert(spec.key.to_string(), property(spec)?);
    }
    let groups: Vec<Json> =
        PARAMETERS.iter().map(|g| json!({"name": g.name, "title": title(g), "keys": g.specs.iter().map(|s| s.key).collect::<Vec<_>>()})).collect();
    let schema = json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "StitchCraft parameters",
        "description": "One design element's embroidery parameters, as JSON values. Generated by `cargo xtask docs` from the parameter registry; the reference pages (params.md) describe the same parameters for people. Keys that are not listed are allowed: StitchCraft keeps them unchanged and reports them (SC-W0105).",
        "type": "object",
        "properties": properties,
        "additionalProperties": true,
        "x-stitchcraft": {"groups": groups},
    });
    serde_json::to_string_pretty(&schema).map(|text| text + "\n").map_err(|e| format!("params.schema.json: {e}"))
}

fn property(spec: &ParamSpec) -> Result<Json, String> {
    let (value, _) = spec.read(spec.default).map_err(|d| format!("`{}`: {}", spec.key, d.message))?;
    let mut property = match spec.kind {
        Kind::Length { min, max, optional } => {
            json!({"type": if optional { json!(["number", "null"]) } else { json!("number") }, "minimum": min, "maximum": max})
        }
        Kind::Angle => json!({"type": "number"}),
        Kind::Percent { min, max } | Kind::Number { min, max } => json!({"type": "number", "minimum": min, "maximum": max}),
        Kind::Count { min, max } => json!({"type": "integer", "minimum": min, "maximum": max}),
        Kind::Toggle => json!({"type": "boolean"}),
        Kind::Choice { options } => json!({"type": "string", "enum": options.iter().map(|o| o.id).collect::<Vec<_>>()}),
        Kind::Seed => json!({"type": ["integer", "string", "null"], "minimum": 0}),
        Kind::LengthList { min, max } | Kind::PercentList { min, max } => {
            json!({"type": "array", "minItems": 1, "maxItems": MAX_LIST, "items": {"type": "number", "minimum": min, "maximum": max}})
        }
        Kind::LengthPair { min, max, optional } | Kind::PercentPair { min, max, optional } => {
            let kinds = if optional { json!(["array", "null"]) } else { json!("array") };
            json!({"type": kinds, "minItems": 1, "maxItems": 2, "items": {"type": "number", "minimum": min, "maximum": max}})
        }
        Kind::CountList { min, max } => {
            json!({"type": "array", "minItems": 1, "maxItems": MAX_LIST, "items": {"type": "integer", "minimum": min, "maximum": max}})
        }
        Kind::Text { max_bytes } => json!({"type": "string", "maxLength": max_bytes}),
    };
    let mut extra = json!({"group": spec.group, "origin": origin(spec.origin), "stability": stability(spec.stability)});
    if !spec.kind.unit().is_empty() {
        extra["unit"] = json!(spec.kind.unit());
    }
    if spec.applies_to != StitchType::ALL {
        extra["applies_to"] = json!(spec.applies_to.iter().map(|t| t.id()).collect::<Vec<_>>());
    }
    if let Some(condition) = spec.visible_when {
        extra["visible_when"] = json!({"key": condition.key, "any_of": condition.any_of});
    }
    if !spec.family_defaults.is_empty() {
        let mut families = serde_json::Map::new();
        for &(family, text) in spec.family_defaults {
            let (value, _) = spec.read(text).map_err(|d| format!("`{}`: {}", spec.key, d.message))?;
            families.insert(family.id().to_string(), json_value(&value));
        }
        extra["family_defaults"] = Json::Object(families);
    }
    if let Origin::InkStitchDeviates { deviation } = spec.origin {
        extra["deviation"] = json!(deviation);
    }
    property["title"] = json!(spec.label);
    property["description"] = json!(unwrapped(&spec.help()));
    property["default"] = json_value(&value);
    property["x-stitchcraft"] = extra;
    Ok(property)
}

/// Markdown with each paragraph's lines joined, for tools that show descriptions as plain text (editor
/// tooltips): a line break inside a paragraph becomes a space; blank lines and list items stay.
fn unwrapped(markdown: &str) -> String {
    let mut out = String::new();
    for line in markdown.lines() {
        let item = line.trim_start().starts_with("- ") || line.trim_start().starts_with("* ");
        let paragraph_goes_on = !out.is_empty() && !out.ends_with('\n') && !line.trim().is_empty() && !item;
        if paragraph_goes_on {
            out.push(' ');
        } else if !out.is_empty() {
            out.push('\n');
        }
        out.push_str(line.trim_end());
    }
    out
}

/// A value as JSON: numbers, `true`/`false`, strings, arrays, and `null` for an empty value.
fn json_value(value: &Value) -> Json {
    match value {
        Value::Length(Some(mm)) => json!(mm.get()),
        Value::Length(None) | Value::Seed(None) | Value::LengthPair(None) | Value::PercentPair(None) => Json::Null,
        Value::Angle(v) | Value::Percent(v) | Value::Number(v) => json!(v),
        Value::Count(n) => json!(n),
        Value::Toggle(on) => json!(on),
        Value::Choice(id) => json!(id),
        Value::Seed(Some(seed)) => json!(seed),
        Value::Lengths(lengths) => json!(lengths.iter().map(|mm| mm.get()).collect::<Vec<_>>()),
        Value::LengthPair(Some([a, b])) if a == b => json!([a.get()]),
        Value::LengthPair(Some(pair)) => json!(pair.map(|mm| mm.get())),
        Value::PercentPair(Some([a, b])) if a == b => json!([a]),
        Value::PercentPair(Some(pair)) => json!(pair),
        Value::Percents(percents) => json!(percents),
        Value::Counts(counts) => json!(counts),
        Value::Text(text) => json!(text),
    }
}

fn origin(origin: Origin) -> &'static str {
    match origin {
        Origin::InkStitch => "inkstitch",
        Origin::InkStitchDeviates { .. } => "inkstitch-deviates",
        Origin::StitchCraft => "stitchcraft",
    }
}

fn stability(stability: Stability) -> &'static str {
    match stability {
        Stability::Stable => "stable",
        Stability::Experimental => "experimental",
        Stability::Deprecated { .. } => "deprecated",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const GROUP: ParamGroup = ParamGroup { name: "TatamiFillParams", help: "", applies_to: &[], specs: &[] };

    #[test]
    fn alternatives_read_as_a_sentence() {
        assert_eq!(either(&["custom"]), "`custom`");
        assert_eq!(either(&["back_forth", "custom"]), "`back_forth` or `custom`");
        assert_eq!(either(&["arrow", "star", "custom"]), "`arrow`, `star` or `custom`");
        assert_eq!(either(&[]), "");
    }

    #[test]
    fn names_become_slugs_and_titles() {
        assert_eq!((slug(&GROUP), title(&GROUP)), ("tatami-fill".to_string(), "Tatami fill parameters".to_string()));
        let common = ParamGroup { name: "CommonParams", ..GROUP };
        assert_eq!((slug(&common), title(&common)), ("common".to_string(), "Common parameters".to_string()));
    }

    #[test]
    fn descriptions_join_the_lines_of_each_paragraph() {
        assert_eq!(unwrapped("One\ntwo.\n\nThree:\n- a\n- b"), "One two.\n\nThree:\n- a\n- b");
    }

    #[test]
    fn every_group_page_has_an_entry_per_key() {
        let anchors: Vec<String> = PARAMETERS.iter().map(|g| anchor(g, "ties")).collect();
        assert_eq!(anchors.first().map(String::as_str), Some("params/common.md#ties"));
        assert!(anchors.contains(&"params/running.md#ties".to_string()), "{anchors:?}");
    }

    #[test]
    fn pages_cover_the_registry_and_the_schema_is_valid_json() {
        let ledger = [Deviation {
            id: "DEV-LCK-001".into(),
            area: "plan/locks".into(),
            summary: "Shapes differ.".into(),
            reason: "Clean room.".into(),
            requirements: vec!["REQ-LCK-002".into()],
        }];
        let pages = pages(&ledger).unwrap();
        let schema = &pages.last().unwrap().1;
        let parsed: Json = serde_json::from_str(schema).unwrap();
        let count = PARAMETERS.iter().map(|g| g.specs.len()).sum::<usize>();
        assert_eq!(parsed["properties"].as_object().map(serde_json::Map::len), Some(count));
        assert_eq!(parsed["properties"]["lock_start_scale_mm"]["default"], json!(0.7));
        assert_eq!(parsed["properties"]["min_stitch_length_mm"]["default"], Json::Null);
        let common = &pages.iter().find(|(path, _)| path.ends_with("params/common.md")).unwrap().1;
        assert!(common.contains("### `lock_custom_start`\n\n**Custom start lock.**"));
        assert!(common.contains("- **Shown when** [`lock_start`](#lock_start) is `custom`"));
        assert!(common.contains("- **Accepts:** one of `0` (At the start and the end), `1` (At the start)"));
        assert!(common.contains("- **Ink/Stitch:** same key; StitchCraft differs (DEV-LCK-001): Shapes differ."));
        assert_eq!(parsed["properties"]["lock_end"]["x-stitchcraft"]["deviation"], json!("DEV-LCK-001"));
        // A family's own default, and what that family accepts since it needs a value.
        assert!(common.contains(
            "- **Accepts:** a length from 0.1 to 25 mm, or empty (0 or less counts as empty); for fills, a length from 0.1 to 25 mm, empty \
             being the default\n- **Default:** empty, and `4` for fills\n"
        ));
        assert_eq!(parsed["properties"]["max_stitch_length_mm"]["x-stitchcraft"]["family_defaults"], json!({"fill": 4.0}));
    }
}
